spring:
    application:
        name: java-spring-ecommerce
    profiles:
        active: test
    jpa:
        open-in-view: true
    mvc:
        servlet:
            path: /ecommerce/api/v1
        
